#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("MonkeyList.Droid.Resource", IsApplication=true)]

namespace MonkeyList.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::MonkeyList.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::MonkeyList.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::MonkeyList.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::MonkeyList.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::MonkeyList.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::MonkeyList.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::MonkeyList.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::MonkeyList.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::MonkeyList.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::MonkeyList.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::MonkeyList.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::MonkeyList.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::MonkeyList.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::MonkeyList.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::MonkeyList.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::MonkeyList.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::MonkeyList.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::MonkeyList.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::MonkeyList.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::MonkeyList.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::MonkeyList.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxBind = global::MonkeyList.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxDropDownItemTemplate = global::MonkeyList.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxGroupItemTemplate = global::MonkeyList.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxItemTemplate = global::MonkeyList.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxLang = global::MonkeyList.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxSource = global::MonkeyList.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxTemplate = global::MonkeyList.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.MvxTemplateSelector = global::MonkeyList.Droid.Resource.Attribute.MvxTemplateSelector;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.layoutManager = global::MonkeyList.Droid.Resource.Attribute.layoutManager;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.reverseLayout = global::MonkeyList.Droid.Resource.Attribute.reverseLayout;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.spanCount = global::MonkeyList.Droid.Resource.Attribute.spanCount;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Attribute.stackFromEnd = global::MonkeyList.Droid.Resource.Attribute.stackFromEnd;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.item_touch_helper_max_drag_scroll_per_frame = global::MonkeyList.Droid.Resource.Dimension.item_touch_helper_max_drag_scroll_per_frame;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.item_touch_helper_swipe_escape_max_velocity = global::MonkeyList.Droid.Resource.Dimension.item_touch_helper_swipe_escape_max_velocity;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Dimension.item_touch_helper_swipe_escape_velocity = global::MonkeyList.Droid.Resource.Dimension.item_touch_helper_swipe_escape_velocity;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.MvvmCrossTagId = global::MonkeyList.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.MvxBindingTagUnique = global::MonkeyList.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Id.item_touch_helper_previous_elevation = global::MonkeyList.Droid.Resource.Id.item_touch_helper_previous_elevation;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxBinding = global::MonkeyList.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxBinding_MvxBind = global::MonkeyList.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxBinding_MvxLang = global::MonkeyList.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxControl = global::MonkeyList.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxControl_MvxTemplate = global::MonkeyList.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxExpandableListView = global::MonkeyList.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::MonkeyList.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxImageView = global::MonkeyList.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxImageView_MvxSource = global::MonkeyList.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxListView = global::MonkeyList.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::MonkeyList.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxListView_MvxItemTemplate = global::MonkeyList.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxRecyclerView = global::MonkeyList.Droid.Resource.Styleable.MvxRecyclerView;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.MvxRecyclerView_MvxTemplateSelector = global::MonkeyList.Droid.Resource.Styleable.MvxRecyclerView_MvxTemplateSelector;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView = global::MonkeyList.Droid.Resource.Styleable.RecyclerView;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_android_descendantFocusability = global::MonkeyList.Droid.Resource.Styleable.RecyclerView_android_descendantFocusability;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_android_orientation = global::MonkeyList.Droid.Resource.Styleable.RecyclerView_android_orientation;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_layoutManager = global::MonkeyList.Droid.Resource.Styleable.RecyclerView_layoutManager;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_reverseLayout = global::MonkeyList.Droid.Resource.Styleable.RecyclerView_reverseLayout;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_spanCount = global::MonkeyList.Droid.Resource.Styleable.RecyclerView_spanCount;
			global::MvvmCross.Droid.Support.V7.RecyclerView.Resource.Styleable.RecyclerView_stackFromEnd = global::MonkeyList.Droid.Resource.Styleable.RecyclerView_stackFromEnd;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010010
			public const int MvxBind = 2130771984;
			
			// aapt resource value: 0x7f010014
			public const int MvxDropDownItemTemplate = 2130771988;
			
			// aapt resource value: 0x7f010015
			public const int MvxGroupItemTemplate = 2130771989;
			
			// aapt resource value: 0x7f010013
			public const int MvxItemTemplate = 2130771987;
			
			// aapt resource value: 0x7f010011
			public const int MvxLang = 2130771985;
			
			// aapt resource value: 0x7f010016
			public const int MvxSource = 2130771990;
			
			// aapt resource value: 0x7f010012
			public const int MvxTemplate = 2130771986;
			
			// aapt resource value: 0x7f01000f
			public const int MvxTemplateSelector = 2130771983;
			
			// aapt resource value: 0x7f010000
			public const int cardBackgroundColor = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int cardCornerRadius = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cardElevation = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cardMaxElevation = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int cardPreventCornerOverlap = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int cardUseCompatPadding = 2130771972;
			
			// aapt resource value: 0x7f010006
			public const int contentPadding = 2130771974;
			
			// aapt resource value: 0x7f01000a
			public const int contentPaddingBottom = 2130771978;
			
			// aapt resource value: 0x7f010007
			public const int contentPaddingLeft = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int contentPaddingRight = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int contentPaddingTop = 2130771977;
			
			// aapt resource value: 0x7f01000b
			public const int layoutManager = 2130771979;
			
			// aapt resource value: 0x7f01000d
			public const int reverseLayout = 2130771981;
			
			// aapt resource value: 0x7f01000c
			public const int spanCount = 2130771980;
			
			// aapt resource value: 0x7f01000e
			public const int stackFromEnd = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f06000c
			public const int black = 2131099660;
			
			// aapt resource value: 0x7f06000f
			public const int border = 2131099663;
			
			// aapt resource value: 0x7f060000
			public const int cardview_dark_background = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int cardview_light_background = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int cardview_shadow_end_color = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int cardview_shadow_start_color = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int colorAccent = 2131099654;
			
			// aapt resource value: 0x7f060004
			public const int colorPrimary = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int colorPrimaryDark = 2131099653;
			
			// aapt resource value: 0x7f06000b
			public const int dark_gray = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int gray = 2131099658;
			
			// aapt resource value: 0x7f060010
			public const int gray_button = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int gray_fab = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int green_button = 2131099666;
			
			// aapt resource value: 0x7f060014
			public const int header_text_color = 2131099668;
			
			// aapt resource value: 0x7f060013
			public const int inventory_gray = 2131099667;
			
			// aapt resource value: 0x7f060008
			public const int light_gray = 2131099656;
			
			// aapt resource value: 0x7f060017
			public const int light_text_color = 2131099671;
			
			// aapt resource value: 0x7f060015
			public const int main_text_color = 2131099669;
			
			// aapt resource value: 0x7f060009
			public const int med_gray = 2131099657;
			
			// aapt resource value: 0x7f060018
			public const int placeholder_text_color = 2131099672;
			
			// aapt resource value: 0x7f06000e
			public const int red = 2131099662;
			
			// aapt resource value: 0x7f060016
			public const int sub_text_color = 2131099670;
			
			// aapt resource value: 0x7f06000d
			public const int text_gray = 2131099661;
			
			// aapt resource value: 0x7f060007
			public const int white = 2131099655;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070000
			public const int cardview_compat_inset_shadow = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int cardview_default_elevation = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int cardview_default_radius = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int item_touch_helper_max_drag_scroll_per_frame = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int item_touch_helper_swipe_escape_max_velocity = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int item_touch_helper_swipe_escape_velocity = 2131165189;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int splash = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080001
			public const int MvvmCrossTagId = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int MvxBindingTagUnique = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int item_touch_helper_previous_elevation = 2131230720;
			
			// aapt resource value: 0x7f080003
			public const int monkey_image = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int monkey_name = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int monkey_origin = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int my_recycler_view = 2131230726;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int listitem_monkey = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int MonkeyView = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int SplashScreen = 2130968578;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f090001
			public const int app_name = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int hello = 2131296256;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int Base_CardView = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int CardView = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int CardView_Dark = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int CardView_Light = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int Theme_Splash = 2131034116;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CardView = new int[]
			{
					16843071,
					16843072,
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978};
			
			// aapt resource value: 1
			public const int CardView_android_minHeight = 1;
			
			// aapt resource value: 0
			public const int CardView_android_minWidth = 0;
			
			// aapt resource value: 2
			public const int CardView_cardBackgroundColor = 2;
			
			// aapt resource value: 3
			public const int CardView_cardCornerRadius = 3;
			
			// aapt resource value: 4
			public const int CardView_cardElevation = 4;
			
			// aapt resource value: 5
			public const int CardView_cardMaxElevation = 5;
			
			// aapt resource value: 7
			public const int CardView_cardPreventCornerOverlap = 7;
			
			// aapt resource value: 6
			public const int CardView_cardUseCompatPadding = 6;
			
			// aapt resource value: 8
			public const int CardView_contentPadding = 8;
			
			// aapt resource value: 12
			public const int CardView_contentPaddingBottom = 12;
			
			// aapt resource value: 9
			public const int CardView_contentPaddingLeft = 9;
			
			// aapt resource value: 10
			public const int CardView_contentPaddingRight = 10;
			
			// aapt resource value: 11
			public const int CardView_contentPaddingTop = 11;
			
			public static int[] MvxBinding = new int[]
			{
					2130771984,
					2130771985};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[]
			{
					2130771986};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[]
			{
					2130771989};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[]
			{
					2130771990};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[]
			{
					2130771987,
					2130771988};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			public static int[] MvxRecyclerView = new int[]
			{
					2130771983};
			
			// aapt resource value: 0
			public const int MvxRecyclerView_MvxTemplateSelector = 0;
			
			public static int[] RecyclerView = new int[]
			{
					16842948,
					16842993,
					2130771979,
					2130771980,
					2130771981,
					2130771982};
			
			// aapt resource value: 1
			public const int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 2
			public const int RecyclerView_layoutManager = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_reverseLayout = 4;
			
			// aapt resource value: 3
			public const int RecyclerView_spanCount = 3;
			
			// aapt resource value: 5
			public const int RecyclerView_stackFromEnd = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
